import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import localFont from 'next/font/local';
const kdamFont = localFont({
  variable: "--font-kdam",
  subsets: ["latin"],
  src: '../../fonts/KdamThmorPro-Regular.ttf'})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rally Jesús María",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kdamFont.variable} antialiased`}
      >
        {children}

      </body>
    </html>
  );
}
